[package]
name = "simple-tinyllama-gui"
version = "0.0.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = [] }
# iced_aw = { version = "0.8.0", features = [ "tabs" ] }
iced_aw = { git = "https://github.com/iced-rs/iced_aw", features = [ "tabs" ] }
llm = "0.1.0"

[profile.dev.package.ggml-sys]
opt-level = 3
